export * from './healthRoutes';
export * from './authRoutes';
export * from './dashboardRoutes';
export * from './planningRoutes';
export * from './motivationRoutes';
export * from './trainingRoutes';
export * from './tutorRoutes';
export * from './notesRoutes';
export * from './boeRoutes';
